//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Iris
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADMINISTRATOR
    {
        public int AdminId { get; set; }
        public string AdminFname { get; set; }
        public string AdminLname { get; set; }
        public string DoB { get; set; }
        public int Age { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string E_mail { get; set; }
    }
}
