//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Iris
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERSON
    {
        public int PersonID { get; set; }
        public string PersonFname { get; set; }
        public string PersonLname { get; set; }
        public System.DateTime DoB { get; set; }
        public string CNIC { get; set; }
        public int Age { get; set; }
        public string Sex { get; set; }
        public byte[] Photo { get; set; }
    
        public virtual IMAGE IMAGE { get; set; }
    }
}
